# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 22:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-z]*$', flags=2, message='Only alphabetic chars allowed.')], verbose_name='Username'),
        ),
    ]
